#!/bin/bash
# =============================================================================
# Generate docker/.env with the host's UID/GID if it does not exist yet.
# - VS Code devcontainer:  runs automatically via initializeCommand
# - CLI (standalone):       run once with `bash docker/init-env.sh`
#
# Existing docker/.env is never overwritten — delete it to regenerate.
# =============================================================================
set -e

ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
    echo "[init-env] $ENV_FILE already exists; leaving untouched"
else
    HOST_UID="$(id -u)"
    HOST_GID="$(id -g)"

    if [ "$HOST_UID" = "0" ] || [ "$HOST_GID" = "0" ]; then
        echo "[init-env] ERROR: do not run as root (got UID=$HOST_UID, GID=$HOST_GID)." >&2
        echo "[init-env] Re-run as a regular user so the container user matches host file ownership." >&2
        if [ -n "${SUDO_USER:-}" ]; then
            echo "[init-env] hint: re-run without sudo (your real user is '$SUDO_USER')." >&2
        fi
        exit 1
    fi

    cat > "$ENV_FILE" <<EOF
# Auto-generated by docker/init-env.sh.
# Edit to override values; see docker/.env.example for all supported variables.
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
EOF

    echo "[init-env] generated $ENV_FILE  (HOST_UID=${HOST_UID}, HOST_GID=${HOST_GID})"
fi
